// ---------------------------------------------------------------------------
// Veriterra.AI — Scoring Engine Type Definitions
// ---------------------------------------------------------------------------
// Every score input and output is pure data. No side effects, no mutation.

// ── Data source classification ──────────────────────────────────────────────
// AI-estimated inputs can never overwrite real lab/manual data.
// The scoring engine reads "source" but doesn't weigh inputs differently —
// trust is asserted at the database layer (immutable snapshots flag source).
export type DataSource =
  | "lab"         // Verified by independent lab testing
  | "manual"      // Entered by a human researcher/expert
  | "ai-estimate" // Generated by the Autonomous AI Engine (clearly flagged)
  ;

// ── Label Accuracy (25%) ──────────────────────────────────────────────────
export interface LabelAccuracyInput {
  /** Measured potency as percentage of label claim (e.g. 95 means 95% of claimed) */
  measuredVsClaimedPercent: number;
  /** Source of this measurement */
  source: DataSource;
  /** Optional notes (e.g. third-party lab name) */
  notes?: string;
}

// ── Purity & Safety (25%) ─────────────────────────────────────────────────
export interface ContaminantReading {
  /** Contaminant name (lead, arsenic, cadmium, mercury, etc.) */
  contaminant: string;
  /** Measured amount in mcg per serving */
  amountMcg: number;
  /** Safety limit in mcg per serving */
  safetyLimitMcg: number;
  /** Source of this measurement */
  source: DataSource;
}

export interface PuritySafetyInput {
  /** Array of contaminant readings */
  contaminants: ContaminantReading[];
  /** Source of purity/safety assessment */
  source: DataSource;
  /** Was the product third-party tested for purity? */
  thirdPartyTested: boolean;
  /** Optional notes */
  notes?: string;
}

// ── Evidence (25%) ────────────────────────────────────────────────────────
export type EvidenceGrade = "A" | "B" | "C" | "D";

export interface ClaimGrade {
  /** The marketed claim (e.g. "supports immune health") */
  claim: string;
  /** Strength of evidence backing this claim */
  grade: EvidenceGrade;
}

export interface EvidenceInput {
  /** Array of graded claims */
  claims: ClaimGrade[];
  /** Source of evidence assessment */
  source: DataSource;
  /** Optional notes */
  notes?: string;
}

// ── Formulation (15%) ─────────────────────────────────────────────────────
export interface FormulationInput {
  /** Is the dose clinically adequate? (0-1, 1 = fully adequate) */
  doseAdequacyScore: number;
  /** Is the ingredient in a bioavailable form? (0-1, 1 = best form) */
  bioavailabilityScore: number;
  /** Is there third-party testing / certification? (0-1) */
  thirdPartyCertified: number;
  /** Source of this assessment */
  source: DataSource;
  /** Notes */
  notes?: string;
}

// ── Value (10%) ───────────────────────────────────────────────────────────
export interface ValueInput {
  /** Cost per clinically effective dose in USD */
  costPerEffectiveDose: number;
  /** Category-average cost per effective dose in USD */
  categoryBenchmarkCost: number;
  /** Source */
  source: DataSource;
  /** Notes */
  notes?: string;
}

// ── Composite input ───────────────────────────────────────────────────────
export interface ScoringInput {
  labelAccuracy: LabelAccuracyInput;
  puritySafety: PuritySafetyInput;
  evidence: EvidenceInput;
  formulation: FormulationInput;
  value: ValueInput;
}

// ── Dimension scores (each 0–100) ─────────────────────────────────────────
export interface DimensionScores {
  labelAccuracy: number;
  puritySafety: number;
  evidence: number;
  formulation: number;
  value: number;
}

// ── Verdict types ─────────────────────────────────────────────────────────
export type VerdictLabel =
  | "Worth taking"
  | "Solid choice"
  | "Mixed"
  | "Skip it";

// ── Immutable snapshot ────────────────────────────────────────────────────
export const SCORING_METHODOLOGY_VERSION = "1.0.0";

export interface ScoringSnapshot {
  /** Unique snapshot ID (UUID v4) */
  snapshotId: string;
  /** Methodology version at time of scoring */
  methodologyVersion: string;
  /** When the score was computed (ISO 8601) */
  computedAt: string;
  /** The product identifier (if available) */
  productId?: string;
  /** The composite score (0–100) */
  compositeScore: number;
  /** Individual dimension scores */
  dimensions: DimensionScores;
  /** Plain-language verdict */
  verdict: VerdictLabel;
  /** The exact inputs that produced this score (immutable) */
  inputs: ScoringInput;
  /** SHA-256 hash of serialized inputs + methodology version (for audit) */
  auditHash: string;
}

// ── Scoring result (without full snapshot for runtime) ────────────────────
export interface ScoringResult {
  compositeScore: number;
  dimensions: DimensionScores;
  verdict: VerdictLabel;
}